if(EXISTS "/home/miron/opencv/proj_test_tests-b858cb2.cmake")
  include("/home/miron/opencv/proj_test_tests-b858cb2.cmake")
else()
  add_test(proj_test_NOT_BUILT-b858cb2 proj_test_NOT_BUILT-b858cb2)
endif()
